// <auto-generated />
namespace HekaEye.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CameraOfRegion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CameraOfRegion));
        
        string IMigrationMetadata.Id
        {
            get { return "202112281929030_CameraOfRegion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
